import { Inter } from 'next/font/google'

import type { Metadata } from 'next'

import './globals.css'

import { Theme } from '@radix-ui/themes'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Theme
          accentColor="orange"
          appearance="dark"
          panelBackground="translucent"
          className="bg-grid-stone-900/50"
        >
          {children}
        </Theme>
      </body>
    </html>
  )
}
