/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import { z as zod } from 'zod'

/**
 * @summary Image To Image
 */
export const imageToImageImageToImagePostBodyNumImagesMaxOne = 8
export const imageToImageImageToImagePostBodyImageSizeHeightMinOne = 0

export const imageToImageImageToImagePostBodyImageSizeHeightMaxOne = 14142
export const imageToImageImageToImagePostBodyImageSizeWidthMinOne = 0

export const imageToImageImageToImagePostBodyImageSizeWidthMaxOne = 14142
export const imageToImageImageToImagePostBodyStrengthMinOne = 0.05

export const imageToImageImageToImagePostBodyStrengthMaxOne = 1

export const imageToImageImageToImagePostBody = zod.object({
  prompt: zod.string(),
  num_images: zod.number().min(1).max(imageToImageImageToImagePostBodyNumImagesMaxOne).optional(),
  image_size: zod
    .object({
      height: zod
        .number()
        .min(imageToImageImageToImagePostBodyImageSizeHeightMinOne)
        .max(imageToImageImageToImagePostBodyImageSizeHeightMaxOne)
        .optional(),
      width: zod
        .number()
        .min(imageToImageImageToImagePostBodyImageSizeWidthMinOne)
        .max(imageToImageImageToImagePostBodyImageSizeWidthMaxOne)
        .optional(),
    })
    .or(
      zod.enum([
        'square_hd',
        'square',
        'portrait_4_3',
        'portrait_16_9',
        'landscape_4_3',
        'landscape_16_9',
      ]),
    )
    .optional(),
  format: zod.enum(['jpeg', 'png']).optional(),
  embeddings: zod
    .array(
      zod.object({
        tokens: zod.array(zod.string()).optional(),
        path: zod.string(),
      }),
    )
    .optional(),
  expand_prompt: zod.boolean().optional(),
  image_url: zod.string(),
  strength: zod
    .number()
    .min(imageToImageImageToImagePostBodyStrengthMinOne)
    .max(imageToImageImageToImagePostBodyStrengthMaxOne)
    .optional(),
  sync_mode: zod.boolean().optional(),
  enable_safety_checker: zod.boolean().optional(),
  num_inference_steps: zod.enum(['1', '2', '4', '8']).optional(),
  seed: zod.number().optional(),
})

export const imageToImageImageToImagePostResponse = zod.object({
  prompt: zod.string(),
  images: zod.array(
    zod.object({
      height: zod.number(),
      content_type: zod.string().optional(),
      url: zod.string(),
      width: zod.number(),
    }),
  ),
  timings: zod.record(zod.string(), zod.number()),
  has_nsfw_concepts: zod.array(zod.boolean()),
  seed: zod.number(),
})

/**
 * @summary Inpainting
 */
export const inpaintingInpaintingPostBodyNumImagesMaxOne = 8
export const inpaintingInpaintingPostBodyImageSizeHeightMinOne = 0

export const inpaintingInpaintingPostBodyImageSizeHeightMaxOne = 14142
export const inpaintingInpaintingPostBodyImageSizeWidthMinOne = 0

export const inpaintingInpaintingPostBodyImageSizeWidthMaxOne = 14142
export const inpaintingInpaintingPostBodyStrengthMinOne = 0.01

export const inpaintingInpaintingPostBodyStrengthMaxOne = 1

export const inpaintingInpaintingPostBody = zod.object({
  prompt: zod.string(),
  num_images: zod.number().min(1).max(inpaintingInpaintingPostBodyNumImagesMaxOne).optional(),
  image_size: zod
    .object({
      height: zod
        .number()
        .min(inpaintingInpaintingPostBodyImageSizeHeightMinOne)
        .max(inpaintingInpaintingPostBodyImageSizeHeightMaxOne)
        .optional(),
      width: zod
        .number()
        .min(inpaintingInpaintingPostBodyImageSizeWidthMinOne)
        .max(inpaintingInpaintingPostBodyImageSizeWidthMaxOne)
        .optional(),
    })
    .or(
      zod.enum([
        'square_hd',
        'square',
        'portrait_4_3',
        'portrait_16_9',
        'landscape_4_3',
        'landscape_16_9',
      ]),
    )
    .optional(),
  format: zod.enum(['jpeg', 'png']).optional(),
  embeddings: zod
    .array(
      zod.object({
        tokens: zod.array(zod.string()).optional(),
        path: zod.string(),
      }),
    )
    .optional(),
  expand_prompt: zod.boolean().optional(),
  image_url: zod.string(),
  strength: zod
    .number()
    .min(inpaintingInpaintingPostBodyStrengthMinOne)
    .max(inpaintingInpaintingPostBodyStrengthMaxOne)
    .optional(),
  sync_mode: zod.boolean().optional(),
  enable_safety_checker: zod.boolean().optional(),
  num_inference_steps: zod.enum(['1', '2', '4', '8']).optional(),
  mask_url: zod.string(),
  seed: zod.number().optional(),
})

export const inpaintingInpaintingPostResponse = zod.object({
  prompt: zod.string(),
  images: zod.array(
    zod.object({
      height: zod.number(),
      content_type: zod.string().optional(),
      url: zod.string(),
      width: zod.number(),
    }),
  ),
  timings: zod.record(zod.string(), zod.number()),
  has_nsfw_concepts: zod.array(zod.boolean()),
  seed: zod.number(),
})

/**
 * @summary Text To Image
 */
export const textToImagePostBodyNumImagesMaxOne = 8
export const textToImagePostBodyImageSizeHeightMinOne = 0

export const textToImagePostBodyImageSizeHeightMaxOne = 14142
export const textToImagePostBodyImageSizeWidthMinOne = 0

export const textToImagePostBodyImageSizeWidthMaxOne = 14142

export const textToImagePostBody = zod.object({
  prompt: zod.string(),
  num_images: zod.number().min(1).max(textToImagePostBodyNumImagesMaxOne).optional(),
  image_size: zod
    .object({
      height: zod
        .number()
        .min(textToImagePostBodyImageSizeHeightMinOne)
        .max(textToImagePostBodyImageSizeHeightMaxOne)
        .optional(),
      width: zod
        .number()
        .min(textToImagePostBodyImageSizeWidthMinOne)
        .max(textToImagePostBodyImageSizeWidthMaxOne)
        .optional(),
    })
    .or(
      zod.enum([
        'square_hd',
        'square',
        'portrait_4_3',
        'portrait_16_9',
        'landscape_4_3',
        'landscape_16_9',
      ]),
    )
    .optional(),
  format: zod.enum(['jpeg', 'png']).optional(),
  embeddings: zod
    .array(
      zod.object({
        tokens: zod.array(zod.string()).optional(),
        path: zod.string(),
      }),
    )
    .optional(),
  expand_prompt: zod.boolean().optional(),
  sync_mode: zod.boolean().optional(),
  enable_safety_checker: zod.boolean().optional(),
  num_inference_steps: zod.enum(['1', '2', '4', '8']).optional(),
  seed: zod.number().optional(),
})

export const textToImagePostResponse = zod.object({
  prompt: zod.string(),
  images: zod.array(
    zod.object({
      height: zod.number(),
      content_type: zod.string().optional(),
      url: zod.string(),
      width: zod.number(),
    }),
  ),
  timings: zod.record(zod.string(), zod.number()),
  has_nsfw_concepts: zod.array(zod.boolean()),
  seed: zod.number(),
})
