// This file is automatically generated by Cosmos. Add it to .gitignore and
// only edit if you know what you're doing.

import { RendererConfig, UserModuleWrappers } from 'react-cosmos-core';

import * as fixture0 from './components/ui/TextareaAutosize.fixture';
import * as fixture1 from './components/navigation/Navigation.fixture';

import * as decorator0 from './components/cosmos.decorator';

export const rendererConfig: RendererConfig = {
  "playgroundUrl": "http://localhost:3344",
  "rendererUrl": "http://localhost:3333/cosmos/<fixture>"
};

const fixtures = {
  'components/ui/TextareaAutosize.fixture.tsx': { module: fixture0 },
  'components/navigation/Navigation.fixture.tsx': { module: fixture1 }
};

const decorators = {
  'components/cosmos.decorator.tsx': { module: decorator0 }
};

export const moduleWrappers: UserModuleWrappers = {
  lazy: false,
  fixtures,
  decorators
};
