/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.12.0.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";
import type * as endpoints_openai from "../endpoints/openai.js";
import type * as files_createImageFromUrl from "../files/createImageFromUrl.js";
import type * as files_optimizeImageFile from "../files/optimizeImageFile.js";
import type * as functions from "../functions.js";
import type * as http from "../http.js";
import type * as images_actions from "../images/actions.js";
import type * as images_manage from "../images/manage.js";
import type * as inference_chatCompletion from "../inference/chatCompletion.js";
import type * as inference_textToImage from "../inference/textToImage.js";
import type * as inference_threadTitleCompletion from "../inference/threadTitleCompletion.js";
import type * as jobs_definitions from "../jobs/definitions.js";
import type * as jobs_runner from "../jobs/runner.js";
import type * as lib_openai from "../lib/openai.js";
import type * as lib_paramInputs from "../lib/paramInputs.js";
import type * as lib_sharp from "../lib/sharp.js";
import type * as providers_aws from "../providers/aws.js";
import type * as providers_clerk from "../providers/clerk.js";
import type * as providers_fal_fast_animatediff from "../providers/fal/fast_animatediff.js";
import type * as providers_fal_fast_lightning_sdxl from "../providers/fal/fast_lightning_sdxl.js";
import type * as providers_fal_hyper_sdxl from "../providers/fal/hyper_sdxl.js";
import type * as providers_fal_illusion_diffusion from "../providers/fal/illusion_diffusion.js";
import type * as providers_fal_imageutils from "../providers/fal/imageutils.js";
import type * as providers_fal_lora from "../providers/fal/lora.js";
import type * as providers_fal_pixart_sigma from "../providers/fal/pixart_sigma.js";
import type * as providers_fal from "../providers/fal.js";
import type * as providers_openai from "../providers/openai.js";
import type * as providers_sinkin from "../providers/sinkin.js";
import type * as providers_types from "../providers/types.js";
import type * as rules from "../rules.js";
import type * as shared_defaults from "../shared/defaults.js";
import type * as shared_entities from "../shared/entities.js";
import type * as shared_models from "../shared/models.js";
import type * as shared_structures from "../shared/structures.js";
import type * as shared_utils from "../shared/utils.js";
import type * as threads_mutate from "../threads/mutate.js";
import type * as threads_query from "../threads/query.js";
import type * as types from "../types.js";
import type * as users from "../users.js";
import type * as utils from "../utils.js";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
declare const fullApi: ApiFromModules<{
  "endpoints/openai": typeof endpoints_openai;
  "files/createImageFromUrl": typeof files_createImageFromUrl;
  "files/optimizeImageFile": typeof files_optimizeImageFile;
  functions: typeof functions;
  http: typeof http;
  "images/actions": typeof images_actions;
  "images/manage": typeof images_manage;
  "inference/chatCompletion": typeof inference_chatCompletion;
  "inference/textToImage": typeof inference_textToImage;
  "inference/threadTitleCompletion": typeof inference_threadTitleCompletion;
  "jobs/definitions": typeof jobs_definitions;
  "jobs/runner": typeof jobs_runner;
  "lib/openai": typeof lib_openai;
  "lib/paramInputs": typeof lib_paramInputs;
  "lib/sharp": typeof lib_sharp;
  "providers/aws": typeof providers_aws;
  "providers/clerk": typeof providers_clerk;
  "providers/fal/fast_animatediff": typeof providers_fal_fast_animatediff;
  "providers/fal/fast_lightning_sdxl": typeof providers_fal_fast_lightning_sdxl;
  "providers/fal/hyper_sdxl": typeof providers_fal_hyper_sdxl;
  "providers/fal/illusion_diffusion": typeof providers_fal_illusion_diffusion;
  "providers/fal/imageutils": typeof providers_fal_imageutils;
  "providers/fal/lora": typeof providers_fal_lora;
  "providers/fal/pixart_sigma": typeof providers_fal_pixart_sigma;
  "providers/fal": typeof providers_fal;
  "providers/openai": typeof providers_openai;
  "providers/sinkin": typeof providers_sinkin;
  "providers/types": typeof providers_types;
  rules: typeof rules;
  "shared/defaults": typeof shared_defaults;
  "shared/entities": typeof shared_entities;
  "shared/models": typeof shared_models;
  "shared/structures": typeof shared_structures;
  "shared/utils": typeof shared_utils;
  "threads/mutate": typeof threads_mutate;
  "threads/query": typeof threads_query;
  types: typeof types;
  users: typeof users;
  utils: typeof utils;
}>;
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;
