import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'pabel 💖',
  description: 'Generated by create next app',
  viewport: {
    width: 'device-width',
    initialScale: 1,
    maximumScale: 1,
    userScalable: false,
  },
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>{children}</body>
    </html>
  )
}

/* 
  bg-[url('/backgrounds/random-shapes.svg')] bg-[length:64px_64px]

  base-200 rgb(242, 242, 242)
  base-300 rgb(229, 230, 230) #e5e6e6
*/
