/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { File } from './file'

export interface AnimateDiffT2VOutput {
  /** Seed used for generating the video. */
  seed: number
  /** Generated video file. */
  video: File
}
