/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export interface DepthMapInput {
  /** a */
  a?: number
  /** bg_th */
  bg_th?: number
  /** depth_and_normal */
  depth_and_normal?: boolean
  /** Input image url. */
  image_url: string
}
