/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export interface Embedding {
  /** URL or the path to the embedding weights. */
  path: string
  /** 
            The tokens to map the embedding weights to. Use these tokens in your prompts.
         */
  tokens?: string[]
}
