/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export interface File {
  /** The mime type of the file. */
  content_type?: string
  /** The name of the file. It will be auto-generated if not provided. */
  file_name?: string
  /** The size of the file in bytes. */
  file_size?: number
  /** The URL where the file can be downloaded from. */
  url: string
}
