/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { Image } from './image'

export interface IllusionDiffusionOutput {
  /** The generated image file info. */
  image: Image
  /** 
            Seed of the generated Image. It will be the same value of the one passed in the
            input or the randomly generated that was used in case none was passed.
         */
  seed: number
}
