/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

/**
 * Scheduler / sampler to use for the image denoising process.
 */
export type IllusionDiffusionInputScheduler =
  (typeof IllusionDiffusionInputScheduler)[keyof typeof IllusionDiffusionInputScheduler]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const IllusionDiffusionInputScheduler = {
  'DPM++_Karras_SDE': 'DPM++ Karras SDE',
  Euler: 'Euler',
} as const
