/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

/**
 * Scheduler / sampler to use for the image denoising process.
 */
export type ImageToImageInputScheduler =
  (typeof ImageToImageInputScheduler)[keyof typeof ImageToImageInputScheduler]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ImageToImageInputScheduler = {
  'DPM++_2M': 'DPM++ 2M',
  'DPM++_2M_Karras': 'DPM++ 2M Karras',
  'DPM++_2M_SDE': 'DPM++ 2M SDE',
  'DPM++_2M_SDE_Karras': 'DPM++ 2M SDE Karras',
  Euler: 'Euler',
  Euler_A: 'Euler A',
  LCM: 'LCM',
} as const
