/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

/**
 * The format of the generated image.
 */
export type ImageToImageHyperInputFormat =
  (typeof ImageToImageHyperInputFormat)[keyof typeof ImageToImageHyperInputFormat]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ImageToImageHyperInputFormat = {
  jpeg: 'jpeg',
  png: 'png',
} as const
