/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export interface ImageSize {
  /**
   * The height of the generated image.
   * @maximum 14142
   */
  height?: number
  /**
   * The width of the generated image.
   * @maximum 14142
   */
  width?: number
}
