/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export interface LoraWeight {
  /** URL or the path to the LoRA weights. */
  path: string
  /**
   * 
            The scale of the LoRA weight. This is used to scale the LoRA weight
            before merging it with the base model.
        
   * @minimum 0
   * @maximum 1
   */
  scale?: number
}
