/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export interface MarigoldDepthMapInput {
  /**
   * Number of predictions to average over. Defaults to `10`. The higher the number, the more accurate the result, but the slower the inference.
   * @minimum 2
   * @maximum 50
   */
  ensemble_size?: number
  /** Input image url. */
  image_url: string
  /**
   * Number of denoising steps. Defaults to `10`. The higher the number, the more accurate the result, but the slower the inference.
   * @minimum 2
   * @maximum 50
   */
  num_inference_steps?: number
  /**
   * Maximum processing resolution. Defaults `0` which means it uses the size of the input image.
   * @minimum 0
   * @maximum 2048
   */
  processing_res?: number
}
