/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { PixArtSigmaInputImageSize } from './pixArtSigmaInputImageSize'
import type { PixArtSigmaInputScheduler } from './pixArtSigmaInputScheduler'
import type { PixArtSigmaInputStyle } from './pixArtSigmaInputStyle'

export interface PixArtSigmaInput {
  /** If set to true, the safety checker will be enabled. */
  enable_safety_checker?: boolean
  /**
   * 
            The CFG (Classifier Free Guidance) scale is a measure of how close you want
            the model to stick to your prompt when looking for a related image to show you.
        
   * @minimum 1
   * @maximum 10
   */
  guidance_scale?: number
  /** The size of the generated image. */
  image_size?: PixArtSigmaInputImageSize
  /** 
            The negative prompt to use. Use it to address details that you don't want
            in the image. This could be colors, objects, scenery and even the small details
            (e.g. moustache, blurry, low resolution).
         */
  negative_prompt?: string
  /**
   * The number of images to generate.
   * @minimum 1
   * @maximum 8
   */
  num_images?: number
  /**
   * The number of inference steps to perform.
   * @minimum 5
   * @maximum 50
   */
  num_inference_steps?: number
  /** The prompt to use for generating the image. Be as descriptive as possible for best results. */
  prompt: string
  /** The scheduler to use for the model. */
  scheduler?: PixArtSigmaInputScheduler
  /** 
            The same seed and the same prompt given to the same version of Stable Diffusion
            will output the same image every time.
         */
  seed?: number
  /** The style to apply to the image. */
  style?: PixArtSigmaInputStyle
  /** 
            If set to true, the function will wait for the image to be generated and uploaded
            before returning the response. This will increase the latency of the function but
            it allows you to get the image directly in the response without going through the CDN.
         */
  sync_mode?: boolean
}
