/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

/**
 * The scheduler to use for the model.
 */
export type PixArtSigmaInputScheduler =
  (typeof PixArtSigmaInputScheduler)[keyof typeof PixArtSigmaInputScheduler]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PixArtSigmaInputScheduler = {
  'DPM-SOLVER': 'DPM-SOLVER',
  'SA-SOLVER': 'SA-SOLVER',
} as const
