/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

/**
 * The architecture of the model to use. If an HF model is used, it will be automatically detected. Otherwise will assume depending on the model name (whether XL is in the name or not).
 */
export type TextToImageInputModelArchitecture =
  (typeof TextToImageInputModelArchitecture)[keyof typeof TextToImageInputModelArchitecture]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TextToImageInputModelArchitecture = {
  sd: 'sd',
  sdxl: 'sdxl',
} as const
