/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

/**
 * Model to use for upscaling
 */
export type UpscaleInputModel = (typeof UpscaleInputModel)[keyof typeof UpscaleInputModel]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpscaleInputModel = {
  RealESRGAN_x4plus: 'RealESRGAN_x4plus',
  RealESRGAN_x2plus: 'RealESRGAN_x2plus',
  RealESRGAN_x4plus_anime_6B: 'RealESRGAN_x4plus_anime_6B',
  RealESRGAN_x4_v3: 'RealESRGAN_x4_v3',
  RealESRGAN_x4_wdn_v3: 'RealESRGAN_x4_wdn_v3',
  RealESRGAN_x4_anime_v3: 'RealESRGAN_x4_anime_v3',
} as const
