/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type AnimateDiffV2VInputMotionsItem =
  (typeof AnimateDiffV2VInputMotionsItem)[keyof typeof AnimateDiffV2VInputMotionsItem]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AnimateDiffV2VInputMotionsItem = {
  'zoom-out': 'zoom-out',
  'zoom-in': 'zoom-in',
  'pan-left': 'pan-left',
  'pan-right': 'pan-right',
  'tilt-up': 'tilt-up',
  'tilt-down': 'tilt-down',
} as const
