/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export interface ControlNet {
  /**
   * 
            The scale of the control net weight. This is used to scale the control net weight
            before merging it with the base model.
        
   * @minimum 0
   * @maximum 2
   */
  conditioning_scale?: number
  /**
   * 
            The percentage of the image to end applying the controlnet in terms of the total timesteps.
        
   * @minimum 0
   * @maximum 1
   */
  end_percentage?: number
  /** URL of the image to be used as the control net. */
  image_url: string
  /** URL or the path to the control net weights. */
  path: string
  /**
   * 
            The percentage of the image to start applying the controlnet in terms of the total timesteps.
        
   * @minimum 0
   * @maximum 1
   */
  start_percentage?: number
}
