/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { IllusionDiffusionInputImageSize } from './illusionDiffusionInputImageSize'
import type { IllusionDiffusionInputScheduler } from './illusionDiffusionInputScheduler'

export interface IllusionDiffusionInput {
  /**
   * @minimum 0
   * @maximum 1
   */
  control_guidance_end?: number
  /**
   * @minimum 0
   * @maximum 1
   */
  control_guidance_start?: number
  /** The scale of the ControlNet. */
  controlnet_conditioning_scale?: number
  /**
   * 
            The CFG (Classifier Free Guidance) scale is a measure of how close you want
            the model to stick to your prompt when looking for a related image to show you.
        
   * @maximum 50
   */
  guidance_scale?: number
  /** 
            The size of the generated image. You can choose between some presets or
            custom height and width that **must be multiples of 8**.
         */
  image_size?: IllusionDiffusionInputImageSize
  /** Input image url. */
  image_url: string
  /** 
            The negative prompt to use. Use it to address details that you don't want
            in the image. This could be colors, objects, scenery and even the small details
            (e.g. moustache, blurry, low resolution).
         */
  negative_prompt?: string
  /**
   * 
            Increasing the amount of steps tells Stable Diffusion that it should take more steps
            to generate your final result which can increase the amount of detail in your image.
        
   * @minimum 0
   * @maximum 80
   */
  num_inference_steps?: number
  /** The prompt to use for generating the image. Be as descriptive as possible for best results. */
  prompt: string
  /** Scheduler / sampler to use for the image denoising process. */
  scheduler?: IllusionDiffusionInputScheduler
  /** 
            Seed of the generated Image. It will be the same value of the one passed in the
            input or the randomly generated that was used in case none was passed.
         */
  seed?: number
}
