/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { Embedding } from './embedding'
import type { ImageToImageHyperInputFormat } from './imageToImageHyperInputFormat'
import type { ImageToImageHyperInputImageSize } from './imageToImageHyperInputImageSize'
import type { ImageToImageHyperInputNumInferenceSteps } from './imageToImageHyperInputNumInferenceSteps'

export interface ImageToImageHyperInput {
  /** The list of embeddings to use. */
  embeddings?: Embedding[]
  /** If set to true, the safety checker will be enabled. */
  enable_safety_checker?: boolean
  /** If set to true, the prompt will be expanded with additional prompts. */
  expand_prompt?: boolean
  /** The format of the generated image. */
  format?: ImageToImageHyperInputFormat
  /** The size of the generated image. */
  image_size?: ImageToImageHyperInputImageSize
  /** The URL of the image to use as a starting point for the generation. */
  image_url: string
  /**
   * The number of images to generate.
   * @minimum 1
   * @maximum 8
   */
  num_images?: number
  /** The number of inference steps to perform. */
  num_inference_steps?: ImageToImageHyperInputNumInferenceSteps
  /** The prompt to use for generating the image. Be as descriptive as possible for best results. */
  prompt: string
  /** 
            The same seed and the same prompt given to the same version of Stable Diffusion
            will output the same image every time.
         */
  seed?: number
  /**
   * determines how much the generated image resembles the initial image
   * @minimum 0.05
   * @maximum 1
   */
  strength?: number
  /** 
            If set to true, the function will wait for the image to be generated and uploaded
            before returning the response. This will increase the latency of the function but
            it allows you to get the image directly in the response without going through the CDN.
         */
  sync_mode?: boolean
}
