/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

/**
 * The number of inference steps to perform.
 */
export type InpaintingLightningInputNumInferenceSteps =
  (typeof InpaintingLightningInputNumInferenceSteps)[keyof typeof InpaintingLightningInputNumInferenceSteps]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const InpaintingLightningInputNumInferenceSteps = {
  NUMBER_1: '1',
  NUMBER_2: '2',
  NUMBER_4: '4',
  NUMBER_8: '8',
} as const
