/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export interface IPAdapter {
  /** URL or the path to the image encoder weights. */
  image_encoder_path?: string
  /** Subpath to the image encoder weights. */
  image_encoder_subpath?: string
  /** URL of the image to be used as the IP adapter. */
  ip_adapter_image_url?: string
  /** Subfolder in the model directory where the IP adapter weights are stored. */
  model_subfolder?: string
  /** URL or the path to the IP adapter weights. */
  path?: string
  /**
   * 
            The scale of the IP adapter weight. This is used to scale the IP adapter weight
            before merging it with the base model.
        
   * @minimum 0
   */
  scale?: number
  /** Name of the weight file. */
  weight_name?: string
}
