/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export interface NSFWImageDetectionOutput {
  /** The probability of the image being NSFW. */
  nsfw_probability: number
}
