/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

/**
 * The timings of the different steps of the generation process.
 */
export type PixArtSigmaOutputTimings = { [key: string]: number }
