/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

/**
 * The style to apply to the image.
 */
export type PixArtSigmaInputStyle =
  (typeof PixArtSigmaInputStyle)[keyof typeof PixArtSigmaInputStyle]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PixArtSigmaInputStyle = {
  '(No_style)': '(No style)',
  Cinematic: 'Cinematic',
  Photographic: 'Photographic',
  Anime: 'Anime',
  Manga: 'Manga',
  Digital_Art: 'Digital Art',
  Pixel_art: 'Pixel art',
  Fantasy_art: 'Fantasy art',
  Neonpunk: 'Neonpunk',
  '3D_Model': '3D Model',
} as const
