/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export interface SamInput {
  /** Attempt better quality output using morphologyEx */
  better_quality?: boolean
  /** Output black and white, multiple masks will be combined into one mask */
  black_white?: boolean
  /** Coordinates for multiple boxes, e.g. [[x,y,w,h],[x2,y2,w2,h2]] */
  box_prompt?: unknown[][]
  /** Object confidence threshold */
  confidence?: number
  /** Url to input image */
  image_url: string
  /** Invert mask colors */
  invert?: boolean
  /** IOU threshold for filtering the annotations */
  iou?: number
  /** Label for point, [1,0], 0 = background, 1 = foreground */
  point_label?: number[]
  /** Coordinates for multiple points [[x1,y1],[x2,y2]] */
  point_prompt?: unknown[][]
  /** Draw high-resolution segmentation masks */
  retina?: boolean
  /** Image size */
  size?: number
  /** The prompt to use when generating masks */
  text_prompt?: string
  /** Draw the edges of the masks */
  with_contours?: boolean
}
