/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { ImageSize } from './imageSize'

/**
 * 
            The size of the generated image. You can choose between some presets or custom height and width
            that **must be multiples of 8**.
        
 */
export type TextToImageInputImageSize =
  | ImageSize
  | 'square_hd'
  | 'square'
  | 'portrait_4_3'
  | 'portrait_16_9'
  | 'landscape_4_3'
  | 'landscape_16_9'
