/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { UpscaleInputModel } from './upscaleInputModel'

export interface UpscaleInput {
  /** Upscaling a face */
  face?: boolean
  /** Url to input image */
  image_url: string
  /** Model to use for upscaling */
  model?: UpscaleInputModel
  /** Rescaling factor */
  scale?: number
  /** Tile size. Default is 0, that is no tile. When encountering the out-of-GPU-memory issue, please specify it, e.g., 400 or 200 */
  tile?: number
}
