/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { Image } from './image'

export interface UpscaleOutput {
  /** Upscaled image */
  image: Image
}
